#ifndef SCHUNK_EGP40_CONTROL__VISIBILITY_CONTROL_H_
#define SCHUNK_EGP40_CONTROL__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define SCHUNK_EGP40_CONTROL__VISIBILITY_EXPORT __attribute__((dllexport))
#define SCHUNK_EGP40_CONTROL__VISIBILITY_IMPORT __attribute__((dllimport))
#else
#define SCHUNK_EGP40_CONTROL__VISIBILITY_EXPORT __declspec(dllexport)
#define SCHUNK_EGP40_CONTROL__VISIBILITY_IMPORT __declspec(dllimport)
#endif
#ifdef SCHUNK_EGP40_CONTROL__VISIBILITY_BUILDING_DLL
#define SCHUNK_EGP40_CONTROL__VISIBILITY_PUBLIC SCHUNK_EGP40_CONTROL__VISIBILITY_EXPORT
#else
#define SCHUNK_EGP40_CONTROL__VISIBILITY_PUBLIC SCHUNK_EGP40_CONTROL__VISIBILITY_IMPORT
#endif
#define SCHUNK_EGP40_CONTROL__VISIBILITY_PUBLIC_TYPE SCHUNK_EGP40_CONTROL__VISIBILITY_PUBLIC
#define SCHUNK_EGP40_CONTROL__VISIBILITY_LOCAL
#else
#define SCHUNK_EGP40_CONTROL__VISIBILITY_EXPORT __attribute__((visibility("default")))
#define SCHUNK_EGP40_CONTROL__VISIBILITY_IMPORT
#if __GNUC__ >= 4
#define SCHUNK_EGP40_CONTROL__VISIBILITY_PUBLIC __attribute__((visibility("default")))
#define SCHUNK_EGP40_CONTROL__VISIBILITY_LOCAL __attribute__((visibility("hidden")))
#else
#define SCHUNK_EGP40_CONTROL__VISIBILITY_PUBLIC
#define SCHUNK_EGP40_CONTROL__VISIBILITY_LOCAL
#endif
#define SCHUNK_EGP40_CONTROL__VISIBILITY_PUBLIC_TYPE
#endif

#endif // SCHUNK_EGP40_CONTROL__VISIBILITY_CONTROL_H_
